FROM node:22 AS web-builder

WORKDIR /web/frps
COPY web/frps/ ./
RUN npm install
RUN npm run build

FROM --platform=$BUILDPLATFORM golang:1.24 AS building

ARG TARGETOS
ARG TARGETARCH

COPY . /building
COPY --from=web-builder /web/frps/dist /building/web/frps/dist
WORKDIR /building

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH make frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
