FROM node:22 AS web-builder

WORKDIR /web/frpc
COPY web/frpc/ ./
RUN npm install
RUN npm run build

FROM --platform=$BUILDPLATFORM golang:1.24 AS building

ARG TARGETOS
ARG TARGETARCH

COPY . /building
COPY --from=web-builder /web/frpc/dist /building/web/frpc/dist
WORKDIR /building

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH make frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]