FROM --platform=$BUILDPLATFORM golang:1.24 AS building

ARG TARGETOS
ARG TARGETARCH

COPY . /building
WORKDIR /building

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH make frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
