FROM --platform=$BUILDPLATFORM golang:1.23 AS building

ARG TARGETOS
ARG TARGETARCH

COPY . /building
WORKDIR /building

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH make frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]